Add ClickHouse data schema management (#81)
When ClickHouse data schema is updated in a new release, users using Persistent Volume
to deploy their ClickHouse will encounter the problem that the old data schema does not
match the new one, and have to lose all the old data.

To deal with this problem, this PR introduces version control to ClickHouse data schema, which
detects the data schema version when initializing ClickHouse.

An upgrading from version N-1 e2e test is also added in this PR.

Signed-off-by: Yanjun Zhou <zhouya@vmware.com>

diff --git a/build/yamls/flow-visibility.yml b/build/yamls/flow-visibility.yml
--- a/build/yamls/flow-visibility.yml
+++ b/build/yamls/flow-visibility.yml
@@ -53,7 +53,263 @@ subjects:
 ---
 apiVersion: v1
 data:
-  create_table.sh: |-
+  0-1-0_0-2-0.sql: |
+    --Create a table to store records
+    CREATE TABLE IF NOT EXISTS flows_local (
+        timeInserted DateTime DEFAULT now(),
+        flowStartSeconds DateTime,
+        flowEndSeconds DateTime,
+        flowEndSecondsFromSourceNode DateTime,
+        flowEndSecondsFromDestinationNode DateTime,
+        flowEndReason UInt8,
+        sourceIP String,
+        destinationIP String,
+        sourceTransportPort UInt16,
+        destinationTransportPort UInt16,
+        protocolIdentifier UInt8,
+        packetTotalCount UInt64,
+        octetTotalCount UInt64,
+        packetDeltaCount UInt64,
+        octetDeltaCount UInt64,
+        reversePacketTotalCount UInt64,
+        reverseOctetTotalCount UInt64,
+        reversePacketDeltaCount UInt64,
+        reverseOctetDeltaCount UInt64,
+        sourcePodName String,
+        sourcePodNamespace String,
+        sourceNodeName String,
+        destinationPodName String,
+        destinationPodNamespace String,
+        destinationNodeName String,
+        destinationClusterIP String,
+        destinationServicePort UInt16,
+        destinationServicePortName String,
+        ingressNetworkPolicyName String,
+        ingressNetworkPolicyNamespace String,
+        ingressNetworkPolicyRuleName String,
+        ingressNetworkPolicyRuleAction UInt8,
+        ingressNetworkPolicyType UInt8,
+        egressNetworkPolicyName String,
+        egressNetworkPolicyNamespace String,
+        egressNetworkPolicyRuleName String,
+        egressNetworkPolicyRuleAction UInt8,
+        egressNetworkPolicyType UInt8,
+        tcpState String,
+        flowType UInt8,
+        sourcePodLabels String,
+        destinationPodLabels String,
+        throughput UInt64,
+        reverseThroughput UInt64,
+        throughputFromSourceNode UInt64,
+        throughputFromDestinationNode UInt64,
+        reverseThroughputFromSourceNode UInt64,
+        reverseThroughputFromDestinationNode UInt64,
+        trusted UInt8 DEFAULT 0
+    ) engine=ReplicatedMergeTree('/clickhouse/tables/{shard}/{database}/{table}', '{replica}')
+    ORDER BY (timeInserted, flowEndSeconds)
+    TTL timeInserted + INTERVAL 12 HOUR
+    SETTINGS merge_with_ttl_timeout = 14400;
+
+    --Move data from old table and drop old tables
+    INSERT INTO flows_local SELECT * FROM flows;
+    DROP TABLE flows;
+    DROP VIEW flows_pod_view;
+    DROP VIEW flows_node_view;
+    DROP VIEW flows_policy_view;
+
+    --Create a Materialized View to aggregate data for pods
+    CREATE MATERIALIZED VIEW IF NOT EXISTS flows_pod_view_local
+    ENGINE = ReplicatedSummingMergeTree('/clickhouse/tables/{shard}/{database}/{table}', '{replica}')
+    ORDER BY (
+        timeInserted,
+        flowEndSeconds,
+        flowEndSecondsFromSourceNode,
+        flowEndSecondsFromDestinationNode,
+        sourcePodName,
+        destinationPodName,
+        destinationIP,
+        destinationServicePort,
+        destinationServicePortName,
+        flowType,
+        sourcePodNamespace,
+        destinationPodNamespace,
+        sourceTransportPort,
+        destinationTransportPort)
+    TTL timeInserted + INTERVAL 12 HOUR
+    SETTINGS merge_with_ttl_timeout = 14400
+    POPULATE
+    AS SELECT
+        timeInserted,
+        flowEndSeconds,
+        flowEndSecondsFromSourceNode,
+        flowEndSecondsFromDestinationNode,
+        sourcePodName,
+        destinationPodName,
+        destinationIP,
+        destinationServicePort,
+        destinationServicePortName,
+        flowType,
+        sourcePodNamespace,
+        destinationPodNamespace,
+        sourceTransportPort,
+        destinationTransportPort,
+        sum(octetDeltaCount) AS octetDeltaCount,
+        sum(reverseOctetDeltaCount) AS reverseOctetDeltaCount,
+        sum(throughput) AS throughput,
+        sum(reverseThroughput) AS reverseThroughput,
+        sum(throughputFromSourceNode) AS throughputFromSourceNode,
+        sum(throughputFromDestinationNode) AS throughputFromDestinationNode
+    FROM flows_local
+    GROUP BY
+        timeInserted,
+        flowEndSeconds,
+        flowEndSecondsFromSourceNode,
+        flowEndSecondsFromDestinationNode,
+        sourcePodName,
+        destinationPodName,
+        destinationIP,
+        destinationServicePort,
+        destinationServicePortName,
+        flowType,
+        sourcePodNamespace,
+        destinationPodNamespace,
+        sourceTransportPort,
+        destinationTransportPort;
+
+    --Create a Materialized View to aggregate data for nodes
+    CREATE MATERIALIZED VIEW IF NOT EXISTS flows_node_view_local
+    ENGINE = ReplicatedSummingMergeTree('/clickhouse/tables/{shard}/{database}/{table}', '{replica}')
+    ORDER BY (
+        timeInserted,
+        flowEndSeconds,
+        flowEndSecondsFromSourceNode,
+        flowEndSecondsFromDestinationNode,
+        sourceNodeName,
+        destinationNodeName,
+        sourcePodNamespace,
+        destinationPodNamespace)
+    TTL timeInserted + INTERVAL 12 HOUR
+    SETTINGS merge_with_ttl_timeout = 14400
+    POPULATE
+    AS SELECT
+        timeInserted,
+        flowEndSeconds,
+        flowEndSecondsFromSourceNode,
+        flowEndSecondsFromDestinationNode,
+        sourceNodeName,
+        destinationNodeName,
+        sourcePodNamespace,
+        destinationPodNamespace,
+        sum(octetDeltaCount) AS octetDeltaCount,
+        sum(reverseOctetDeltaCount) AS reverseOctetDeltaCount,
+        sum(throughput) AS throughput,
+        sum(reverseThroughput) AS reverseThroughput,
+        sum(throughputFromSourceNode) AS throughputFromSourceNode,
+        sum(reverseThroughputFromSourceNode) AS reverseThroughputFromSourceNode,
+        sum(throughputFromDestinationNode) AS throughputFromDestinationNode,
+        sum(reverseThroughputFromDestinationNode) AS reverseThroughputFromDestinationNode
+    FROM flows_local
+    GROUP BY
+        timeInserted,
+        flowEndSeconds,
+        flowEndSecondsFromSourceNode,
+        flowEndSecondsFromDestinationNode,
+        sourceNodeName,
+        destinationNodeName,
+        sourcePodNamespace,
+        destinationPodNamespace;
+
+    --Create a Materialized View to aggregate data for network policies
+    CREATE MATERIALIZED VIEW IF NOT EXISTS flows_policy_view_local
+    ENGINE = ReplicatedSummingMergeTree('/clickhouse/tables/{shard}/{database}/{table}', '{replica}')
+    ORDER BY (
+        timeInserted,
+        flowEndSeconds,
+        flowEndSecondsFromSourceNode,
+        flowEndSecondsFromDestinationNode,
+        egressNetworkPolicyName,
+        egressNetworkPolicyNamespace,
+        egressNetworkPolicyRuleAction,
+        ingressNetworkPolicyName,
+        ingressNetworkPolicyNamespace,
+        ingressNetworkPolicyRuleAction,
+        sourcePodName,
+        sourceTransportPort,
+        sourcePodNamespace,
+        destinationPodName,
+        destinationTransportPort,
+        destinationPodNamespace,
+        destinationServicePort,
+        destinationServicePortName,
+        destinationIP)
+    TTL timeInserted + INTERVAL 12 HOUR
+    SETTINGS merge_with_ttl_timeout = 14400
+    POPULATE
+    AS SELECT
+        timeInserted,
+        flowEndSeconds,
+        flowEndSecondsFromSourceNode,
+        flowEndSecondsFromDestinationNode,
+        egressNetworkPolicyName,
+        egressNetworkPolicyNamespace,
+        egressNetworkPolicyRuleAction,
+        ingressNetworkPolicyName,
+        ingressNetworkPolicyNamespace,
+        ingressNetworkPolicyRuleAction,
+        sourcePodName,
+        sourceTransportPort,
+        sourcePodNamespace,
+        destinationPodName,
+        destinationTransportPort,
+        destinationPodNamespace,
+        destinationServicePort,
+        destinationServicePortName,
+        destinationIP,
+        sum(octetDeltaCount) AS octetDeltaCount,
+        sum(reverseOctetDeltaCount) AS reverseOctetDeltaCount,
+        sum(throughput) AS throughput,
+        sum(reverseThroughput) AS reverseThroughput,
+        sum(throughputFromSourceNode) AS throughputFromSourceNode,
+        sum(reverseThroughputFromSourceNode) AS reverseThroughputFromSourceNode,
+        sum(throughputFromDestinationNode) AS throughputFromDestinationNode,
+        sum(reverseThroughputFromDestinationNode) AS reverseThroughputFromDestinationNode
+    FROM flows_local
+    GROUP BY
+        timeInserted,
+        flowEndSeconds,
+        flowEndSecondsFromSourceNode,
+        flowEndSecondsFromDestinationNode,
+        egressNetworkPolicyName,
+        egressNetworkPolicyNamespace,
+        egressNetworkPolicyRuleAction,
+        ingressNetworkPolicyName,
+        ingressNetworkPolicyNamespace,
+        ingressNetworkPolicyRuleAction,
+        sourcePodName,
+        sourceTransportPort,
+        sourcePodNamespace,
+        destinationPodName,
+        destinationTransportPort,
+        destinationPodNamespace,
+        destinationServicePort,
+        destinationServicePortName,
+        destinationIP;
+
+    --Create a table to store the network policy recommendation results
+    CREATE TABLE IF NOT EXISTS recommendations_local (
+        id String,
+        type String,
+        timeCreated DateTime,
+        yamls String
+    ) engine=ReplicatedMergeTree('/clickhouse/tables/{shard}/{database}/{table}', '{replica}')
+    ORDER BY (timeCreated);
+
+    --Move data from old table and drop the old table
+    INSERT INTO recommendations_local SELECT * FROM recommendations;
+    DROP TABLE recommendations;
+  0-2-0_0-1-0.sql: |
+    -- place holder
+  create_table.sh: |
     #!/usr/bin/env bash
 
     # Copyright 2022 Antrea Authors.
@@ -71,7 +327,8 @@ data:
     # limitations under the License.
 
     # ttlTimeout is calculated by the smaller value in its default value and TTL
-    set -e
+
+    function createTable {
     clickhouse client -n -h 127.0.0.1 <<-EOSQL
         --Create a table to store records
         CREATE TABLE IF NOT EXISTS flows_local (
@@ -332,6 +589,163 @@ data:
         CREATE TABLE IF NOT EXISTS recommendations AS recommendations_local
         engine=Distributed('{cluster}', default, recommendations_local, rand());
     EOSQL
+    }
+  init.sh: |
+    #!/usr/bin/env bash
+
+    # Copyright 2022 Antrea Authors.
+    #
+    # Licensed under the Apache License, Version 2.0 (the "License");
+    # you may not use this file except in compliance with the License.
+    # You may obtain a copy of the License at
+    #
+    #      http://www.apache.org/licenses/LICENSE-2.0
+    #
+    # Unless required by applicable law or agreed to in writing, software
+    # distributed under the License is distributed on an "AS IS" BASIS,
+    # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+    # See the License for the specific language governing permissions and
+    # limitations under the License.
+
+    set -e
+
+    THIS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
+
+    source $THIS_DIR/migrate.sh
+    source $THIS_DIR/create_table.sh
+
+    migrate
+    createTable
+    setDataVersion
+  migrate.sh: |
+    #!/usr/bin/env bash
+
+    # Copyright 2022 Antrea Authors.
+    #
+    # Licensed under the Apache License, Version 2.0 (the "License");
+    # you may not use this file except in compliance with the License.
+    # You may obtain a copy of the License at
+    #
+    #      http://www.apache.org/licenses/LICENSE-2.0
+    #
+    # Unless required by applicable law or agreed to in writing, software
+    # distributed under the License is distributed on an "AS IS" BASIS,
+    # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+    # See the License for the specific language governing permissions and
+    # limitations under the License.
+
+    function checkDataVersion {
+        tables=$(clickhouse client -h 127.0.0.1 -q "SHOW TABLES")
+        if [[ $tables == *"migrate_version"* ]]; then
+            dataVersion=$(clickhouse client -h 127.0.0.1 -q "SELECT version FROM migrate_version")
+        elif [[ $tables == *"flows"* ]]; then
+            dataVersion="0.1.0"
+        fi
+    }
+
+    function setDataVersion {
+        tables=$(clickhouse client -h 127.0.0.1 -q "SHOW TABLES")
+        if [[ $tables == *"migrate_version"* ]]; then
+            clickhouse client -h 127.0.0.1 -q "ALTER TABLE migrate_version DELETE WHERE version!=''"
+        else
+            clickhouse client -h 127.0.0.1 -q "CREATE TABLE migrate_version (version String) engine=MergeTree ORDER BY version"
+        fi
+        clickhouse client -h 127.0.0.1 -q "INSERT INTO migrate_version (*) VALUES ('0.2.0')"
+        echo "=== Set data schema version to 0.2.0 ==="
+    }
+
+    function addVersionsToList {
+        if [[ "$versionListStr" != *"$1"* ]]; then
+            versionListStr+="$1,"
+        fi
+    }
+
+    function getMigrationPath {
+        # Get versions based on the SQL file names
+        versionListStr=""
+        for fileName in $(ls "$migratorDir/upgrade")
+        do
+            # fileName upgrading from v0.1.0 to v0.2.0: 0-1-0_0-2-0.sql
+            fileName=$(basename $fileName .sql)
+            versionPair=(${fileName//_/ })
+            addVersionsToList ${versionPair[0]//-/.}
+            addVersionsToList ${versionPair[1]//-/.}
+        done
+        addVersionsToList $dataVersion
+        addVersionsToList $theiaVersion
+        # Sort the versions to generate the migration path
+        versionList=(${versionListStr//,/ })
+        old_IFS=$IFS
+        IFS=$'\n' sortedversionList=($(sort -V <<<"${versionList[*]}"))
+        IFS=$old_IFS
+        # Define the upgrading/downgrading path
+        index=0
+        prev=""
+        for version in "${sortedversionList[@]}"
+        do
+            migratePathStr+="$index:$version, "
+            index=$((index+1))
+            if [[ -z "$prev" ]]; then
+                prev=${version//./-}
+            else
+                curr=${version//./-}
+                UPGRADING_MIGRATORS+=("${prev}_${curr}.sql")
+                DOWNGRADING_MIGRATORS+=("${curr}_${prev}.sql")
+                prev=$curr
+            fi
+        done
+    }
+
+    function version_lt() { test "$(printf '%s\n' "$@" | sort -rV | head -n 1)" != "$1"; }
+
+    function migrate {
+        THIS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
+        migratorDir="/var/lib/clickhouse/migrators"
+        mkdir -p $migratorDir
+
+        checkDataVersion
+        if [[ -z "$dataVersion" ]]; then
+            cp -r $THIS_DIR/migrators/* $migratorDir
+            echo "=== No existing data schema. Migration skipped. ==="
+            return 0
+        fi
+        if [[ -z "$THEIA_VERSION" ]]; then
+            echo "=== Unable to load the environment variable THEIA_VERSION. Migration failed. ==="
+            exit 1
+        fi
+        theiaVersion=$THEIA_VERSION
+
+        migratePathStr=""
+        getMigrationPath
+
+        cp -r $THIS_DIR/migrators/* $migratorDir
+
+        dataVersionIndex=$(echo $migratePathStr | tr ', ' '\n' | grep "$dataVersion" | sed 's/:/ /g' | awk '{print $1}')
+        theiaVersionIndex=$(echo $migratePathStr | tr ', ' '\n' | grep "$theiaVersion" | sed 's/:/ /g' | awk '{print $1}')
+
+        # Update along the path
+        if [[ "$dataVersionIndex" -lt "$theiaVersionIndex" ]]; then
+            for i in $(seq $dataVersionIndex $((theiaVersionIndex-1)) );
+            do
+                if test -f "$migratorDir/upgrade/${UPGRADING_MIGRATORS[$i]}"; then
+                    echo "=== Apply file ${UPGRADING_MIGRATORS[$i]} ==="
+                    clickhouse client -h 127.0.0.1 --queries-file $migratorDir/upgrade/${UPGRADING_MIGRATORS[$i]}
+                fi
+            done
+        # Downgrade along the path
+        elif [[ "$dataVersionIndex" -gt "$theiaVersionIndex" ]]; then
+            for i in $(seq $((dataVersionIndex-1)) -1 $theiaVersionIndex);
+            do
+                if test -f "$migratorDir/downgrade/${DOWNGRADING_MIGRATORS[$i]}"; then
+                    echo "=== Apply file ${DOWNGRADING_MIGRATORS[$i]} ==="
+                    clickhouse client -h 127.0.0.1 --queries-file $migratorDir/downgrade/${DOWNGRADING_MIGRATORS[$i]}
+                fi
+            done
+        else
+            echo "=== Data schema version is the same as Theia version. Migration finished. ==="
+        fi
+        setDataVersion
+    }
 kind: ConfigMap
 metadata:
   name: clickhouse-mounted-configmap
@@ -4786,7 +5200,10 @@ spec:
         type: MaxNumberPerNode
       spec:
         containers:
-        - image: projects.registry.vmware.com/antrea/theia-clickhouse-server:21.11
+        - env:
+          - name: THEIA_VERSION
+            value: 0.2.0
+          image: projects.registry.vmware.com/antrea/theia-clickhouse-server:21.11
           imagePullPolicy: IfNotPresent
           name: clickhouse
           volumeMounts:
@@ -4826,6 +5243,17 @@ spec:
           name: clickhouse-monitor
         volumes:
         - configMap:
+            items:
+            - key: create_table.sh
+              path: create_table.sh
+            - key: init.sh
+              path: init.sh
+            - key: migrate.sh
+              path: migrate.sh
+            - key: 0-1-0_0-2-0.sql
+              path: migrators/upgrade/0-1-0_0-2-0.sql
+            - key: 0-2-0_0-1-0.sql
+              path: migrators/downgrade/0-2-0_0-1-0.sql
             name: clickhouse-mounted-configmap
           name: clickhouse-configmap-volume
         - emptyDir:
